[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
kotlinBip39 = "1.0.9"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
zxing = "3.5.3"
firebaseCrashlyticsBuildtools = "3.0.6"
solanaj = "1.18.0"
xrpl = "2.5.1"
guava = "31.1-android"
lottie = "6.6.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
kotlin-bip39 = { module = "cash.z.ecc.android:kotlin-bip39", version.ref = "kotlinBip39" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
solanaj = { group = "org.p2p", name = "solanaj", version.ref = "solanaj" }
xrpl4j-client = { group = "org.xrpl", name = "xrpl4j-client", version.ref = "xrpl" }
xrpl4j-model = { group = "org.xrpl", name = "xrpl4j-model", version.ref = "xrpl" }
xrpl4j-wallet = { group = "org.xrpl", name = "xrpl4j-wallet", version.ref = "xrpl" }
xrpl4j-keypairs = { group = "org.xrpl", name = "xrpl4j-keypairs", version.ref = "xrpl" }
xrpl4j-crypto-bouncycastle = { group = "org.xrpl", name = "xrpl4j-crypto-bouncycastle", version.ref = "xrpl" }
xrpl4j-address-codec = { group = "org.xrpl", name = "xrpl4j-address-codec", version.ref = "xrpl" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
